[build]
builder = "dockerrun"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
PORT = "8000"
ENV = "production"
DEBUG = "false"